### ISSUE TITLE
[EPIC] CI: Set up our CI

### ISSUE THREAD

**Issue by troublecat55** [Cockatoo-AI-Org/Cockatoo.AI#27]
This is my first time setting up a CI pipeline, I will update TODO's  when necessary.

##### TODO's
- [ ] Default [Creating tasklists with Markdown](https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/creating-a-tasklist#creating-tasklists-with-markdown) on new Github issues
- [ ] Pipeline: Github Action
- [ ] Linting and styling: [Ruff](https://docs.astral.sh/ruff/), black
